sudo: false
language: node_js
node_js:
  - 'stable'
  - '10'
  - '8'
  - '6'
  - '4'
matrix:
  fast_finish: true
branches:
  only:
    - master
cache:
  directories:
    - node_modules
notifications:
  email:
    on_success: never
before_script: 'yarn linter'
script: 'yarn test'
after_script: 'yarn coverage'
